name: Build
on: 
  push:
    branches:
      - develop
env:
  NEXT_VERSION: ""
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitFlow
        run: sudo apt-get install git-flow
        
      - name: Configure GitFlow
        run: git config --global gitflow.branch.master main

      - name: Install bumpversion
        run: pip install bumpversion

      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Init GitFlow with defaults
        run: git flow init -fd

      - name: Get next version
        run: NEXT_VERSION=`bumpversion --dry-run --list --allow-dirty patch | grep new_version | sed -r s,"^.*=",,` && echo NEXT_VERSION=$NEXT_VERSION

      - name: Git flow release start
        run: git flow release start $NEXT_VERSION

      - name: Execute bumpversion
        run: bumpversion --patch

      - name: Update Changelog
        run: |
          npx standard-version --skip.tag=true --skip.bump=true --skip.commit=true \
          commit -m "chore: updated changelog" CHANGELOG.md

      - name: Git flow release finish
        run: git flow release finish $NEXT_VERSION

      - name: Push
        run: git push --all

      #- name: Install semantic-release
      #  run: npm install --save-dev semantic-release @google/semantic-release-replace-plugin @saithodev/semantic-release-backmerge
        
      #- name: Release
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    #NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #  run: npx semantic-release

